name: Arduino CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Python serial library
        run: python3 -m pip install pyserial

      - name: Arduino CLI Core Index Update
        run: |
          arduino-cli config init
          arduino-cli core update-index

      - name: Arduino ESP8266 Platform Installation
        run: arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Arduino ESP32 Platform Installation
        run: arduino-cli core install esp32:esp32@2.0.15

      - name: Arduino RP2040 Platform Installation
        run: arduino-cli core install rp2040:rp2040 --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

      - name: Download Arduino Dependencies
        run: git clone https://github.com/fdivitto/fabgl.git

      - name: Build Arduino library on ESP8266
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 --library src --build-path build examples/model_on_sd/model_on_sd.ino
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 --library src --build-path build examples/xor_example/xor_example.ino

      - name: Build Arduino library on ESP32
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32wrover --library src --build-path build examples/model_on_sd/model_on_sd.ino
          arduino-cli compile --fqbn esp32:esp32:esp32wrover --library src --build-path build examples/xor_example/xor_example.ino
          arduino-cli compile --fqbn esp32:esp32:esp32wrover --library src --library fabgl --build-path build examples/ili9341_xor/ili9341_xor.ino

      - name: Build Arduino library on RP2040
        run: |
          arduino-cli compile --fqbn rp2040:rp2040:rpipico --library src --build-path build examples/model_on_sd/model_on_sd.ino
          arduino-cli compile --fqbn rp2040:rp2040:rpipico --library src --build-path build examples/xor_example/xor_example.ino
