name: Emscripten Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 1.38.40
          actions-cache-folder: 'emsdk-cache'
      
      - name: Verify Emscripten installation
        run: emcc -v

      - name: Building examples via emcc
        run: |
          mkdir -p dist
          emcc -std=c++17 -Isrc src/*.cpp -o dist/basic_example.html examples/basic_example/basic_example.cpp
          emcc -std=c++17 -Isrc src/*.cpp -o dist/model_training.html examples/model_training/model_training.cpp
