name: GCC Build CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Building example programs
        run: |
          mkdir -p dist
          g++ -std=c++17 -Isrc src/*.cpp -o dist/basic_example examples/basic_example/basic_example.cpp
          g++ -std=c++17 -Isrc src/*.cpp -o dist/model_training examples/model_training/model_training.cpp

      - name: Run example programs
        run: |
          ./dist/basic_example
          if [ "${{ matrix.os }}" != "ubuntu-latest" ]; then
            ./dist/model_training
          fi
